#!/bin/bash
#################################
# Author: Tanay
# Date: 05-06-2024
# This script outputs the node health
# version: 1
#################################
set -x # debug mode

df -h


free -g


nproc
